In [3]:
#objects[OOPS]
def test():
    print('test() for function')
    return;
test()

test() for function


In [5]:
class demo:
    def test(self):
        print("test()for the class and method")
        return;
obj=demo() #object creation
obj.test()

test()for the class and method


In [14]:
class demo1:
    def fact(self,n):
        #return factorial
        return
p1=demo1()
p1.fact(5)#120


In [15]:
class demo1:
    def fact(self,n):
        #return factorial
        fact=1
        while(n!=0):
            fact=fact*n;
            n=n-1;
        return fact
p1=demo1()
p1.fact(5)#120


120

In [17]:
#method
#def test(self,para1,para2)

In [22]:
class demo2:
    a=0,b=0
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self):
        print("p1= ",p1)
        print("p2= ",p2)
        

        
c1=demo2();
c1.display()


p1=  <__main__.demo1 object at 0x006B81B0>


NameError: name 'p2' is not defined

In [23]:
class demo2:
    def _init_(self,p1,p2):
        self.p1=p1;
        self.p2=p2;
        
    def add(self):
        return  p1 + p2
c1=demo2(10,20)
print(c1.add(100,200))

TypeError: demo2() takes no arguments

In [24]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [25]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [26]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [27]:

lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(4,)
int32


In [30]:

lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(4,)
float64


In [31]:
a1=np.array([])
print()

In [32]:
#re-shape the given array
#numpy.reshape(arrayname,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
#horizontal stack
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [34]:
#vertical stack
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [36]:
#generate random number from np
a1=np.random.normal(5,0.5,10)
print(a1)

[5.40639925 5.10055048 5.27044015 5.21396011 4.24961827 5.35568104
 4.78315118 4.53101904 4.75195646 5.19603367]


In [41]:
#numpy.zeros()and numpy.one()
#genrate array with all zeros---numpy.zeros()
#NUMPY.ZEROS(SHAPE,dtype=float,order='c')
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [38]:
#np.Z(SHAPE,dtype=float,order='c')
np.ones((2,2),dtype=np.int64)

array([[1, 1],
       [1, 1]], dtype=int64)

In [39]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [46]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [47]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [49]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1  1]]


In [50]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]
